#!/bin/sh
uci get ssr.@general[-1] >/dev/null 2>&1 || \
	uci add ssr general >/dev/null 2>&1
uci get ssr.@transparent_proxy[-1] >/dev/null 2>&1 || \
	uci add ssr transparent_proxy >/dev/null 2>&1
uci get ssr.@socks5_proxy[-1] >/dev/null 2>&1 || \
	uci add ssr socks5_proxy >/dev/null 2>&1
uci get ssr.@port_forward[-1] >/dev/null 2>&1 || \
	uci add ssr port_forward >/dev/null 2>&1
uci get ssr.@access_control[-1] >/dev/null 2>&1 || \
	uci add ssr access_control >/dev/null 2>&1
uci commit ssr
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ssr[-1]
	add ucitrack ssr
	set ucitrack.@ssr[-1].init=ssr
	commit ucitrack
	delete firewall.ssr
	set firewall.ssr=include
	set firewall.ssr.type=script
	set firewall.ssr.path=/var/etc/ssr.include
	set firewall.ssr.reload=1
	commit firewall
EOF
exit 0
